### ISSUE TITLE
Package CLI plugin with krew

### ISSUE THREAD

**Issue by dhiltgen** [vmware-tanzu/buildkit-cli-for-kubectl#5]
See https://krew.sigs.k8s.io/docs/developer-guide/distributing-with-krew/

**Comment by Vad1mo** [comment]
> Looking at perhaps using this to automate things:
> https://github.com/marketplace/actions/krew-plugin-release

There is now https://github.com/rajatjindal/krew-release-bot

Any chance we might help you to get the buildkit-cli-for-kubectl availible as a krew plugin?

**Comment by dhiltgen** [comment]
Good question @Vad1mo.  @mikeroySoft how's your investigation coming?

**Comment by mikeroySoft** [comment]
Well I've got builtkit-cli.yaml written and that is working for me locally.
What I'm a bit unsure of is where it should belong within this repo. 
I haven't started trying the krew-plugin-release GitHub action yet tho, but I'm happy to once we figure out where the plugin  code should live.

**Comment by dhiltgen** [comment]
I haven't investigated this, but from a very quick perusal of what manifests look like, it seems like it has to be generated when we do a release so it has the right checksums and version strings.  The current release process is documented at https://github.com/vmware-tanzu/buildkit-cli-for-kubectl/blob/main/docs/release.md

I think it probably makes sense to implement this in the Makefile so that `make dist` creates the manifest aligned with the artifacts it's producing.  That way you can test locally to ensure it works properly before submitting a PR.  Ultimately the release.yaml file calls this build target and overrides the VERSION with the specfied version from the git tag that triggered the release.

**Comment by mikeroySoft** [comment]
Sorry for not making much progress here... I picked up the ball and got looking into it again, and an approach that was suggested to me would be that right after the [build step ](https://github.com/vmware-tanzu/buildkit-cli-for-kubectl/blob/a6aefeb3970b338c43bf0cfa5f452b2a3ec5e838/.github/workflows/release.yaml#L27-L28), we could add a step like the following to get the checksums and add them [as outputs](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs), using the ::set-output syntax, something like this:
 
   ```
 - name: Generate checksums
      id: checksums
      shell: bash
      env:
        VERSION: ${{ steps.get_version.outputs.VERSION }}
      run: |
        echo "::set-output name=darwin::$( shasum --algorithm 256 darwin-$VERSION.tar | cut -f1 -d ' ' )"
        echo "::set-output name=linux::$( shasum --algorithm 256 linux-$VERSION.tar | cut -f1 -d ' ' )"
        echo "::set-output name=windows::$( shasum --algorithm 256 windows-$VERSION.tar | cut -f1 -d ' ' )"
```
 
We could then consume those outputs (steps.checksums.outputs.darwin, steps.checksums.outputs.linux, steps.checksums.outputs.windows) in a separate step to update the buildkit-cli.yaml.

Still unclear where buildkit-cli.yaml should live tho. I'm sure there's an example I just haven't seen yet tho.

@Vad1mo, would  **_rajatjindal/krew-release-bot_** work in concert _with_ that, or _instead of_ it?

**Comment by dhiltgen** [comment]
We could implement this as discrete steps in the github CI plumbing, but my suspicion is that might be more complicated that way.

If we check in a templatized file called `./buildkit-cli.yaml.tmpl` at the top of the tree that looks something like this (shortened for brevity)
```yaml
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: build
spec:
  version: %%VERSION%%
...
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/vmware-tanzu/buildkit-cli-for-kubectl/releases/download/%%VERSION%%/darwin-refs.tags.%%VERSION%%.tgz
    sha256: %%DARWIN_HASH%%
    bin: kubectl-build
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/vmware-tanzu/buildkit-cli-for-kubectl/releases/download/%%VERSION%%/linux-refs.tags.%%VERSION%%.tgz
    sha256: %%LINUX_HASH%%
...
```

then update the dist target to look something like this...
```make
...
.PHONY: dist
dist: $(CI_BUILD_TARGETS) $(CI_ARCHIVES)
	sed -e "s/%%VERSION%%/$(VERSION)/g" \
	  -e "s/%%DARWIN_HASH%%/$$(shasum --algorithm 256 ./bin/darwin.tgz)/g" \
	  -e "s/%%LINUX_HASH%%/$$(shasum --algorithm 256 ./bin/linux.tgz)/g" \
	  -e ... \
	  ./buildkit-cli.yaml.tmpl > ./bin/buildkit-cli.yaml
```
A major benefit of the above approach is you can test locally without having to iterate through CI on your PR.
(We can make it fancier later with further makefile magic to make the set of platforms more dynamic and tied to `$(CI_ARCHIVES)`)

With that then I think you just need one added block in the release CI to publish that artifact as well.
