### ISSUE TITLE
 2 node(s) didn't match Pod's node affinity.

### ISSUE THREAD

**Issue by Vad1mo** [vmware-tanzu/buildkit-cli-for-kubectl#91]
I updated to latest version 0.1.3 and tried to run a build. 

However I get the error message ' 2 node(s) didn't match Pod's node affinity.'

becasue of this pod anti affinity 

```
podAntiAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app: buildkit
          rootless: 'false'
          runtime: docker
          worker: ''
      topologyKey: kubernetes.io/hostname
```
